#!/bin/sh
set -eu
umask 077
# Only images with a root-owned factory layout prepare their included data partition.
if [ -e /etc/justverify-factory.json ]; then
    /usr/bin/python3 /opt/justverify/scripts/factory_volume.py
fi
install -d -m 0700 -o justverify -g justverify /var/lib/justverify/config /var/lib/justverify/preflight
if [ ! -e /var/lib/justverify/config/managed.conf ]; then
    install -m 0600 -o justverify -g justverify /dev/null /var/lib/justverify/config/managed.conf
fi
install -d -m 0700 -o justverify -g justverify /var/lib/justverify/web
if [ -e /boot/firmware/justverify-owner.json ] || [ -L /boot/firmware/justverify-owner.json ]; then
    if [ ! -f /boot/firmware/justverify-owner.json ] || [ -L /boot/firmware/justverify-owner.json ]; then
        echo 'Invalid owner provisioning file' >&2
        exit 1
    fi
    install -m 0600 -o justverify -g justverify /boot/firmware/justverify-owner.json /var/lib/justverify/web/pending-owner.json
    runuser -u justverify -- /opt/justverify/venv/bin/python /opt/justverify/scripts/web_identity.py /var/lib/justverify/web --owner-file /var/lib/justverify/web/pending-owner.json
    rm /boot/firmware/justverify-owner.json
    sync -f /boot/firmware
else
    runuser -u justverify -- /opt/justverify/venv/bin/python /opt/justverify/scripts/web_identity.py /var/lib/justverify/web
fi
# Node data is prepared only after explicit volume and profile registration.
install -d -m 0700 -o justverify -g justverify /var/lib/justverify/versions /var/lib/justverify/downloads
# Machine identity is generated by systemd; the SSH init unit generates unique host keys.
